# provide node version
FROM node:16.13
# install webpack
RUN npm i webpack -g
# set current location
WORKDIR /usr/src/app
# copy package json and package lock json
COPY package*.json .
# install all dependencies
RUN npm i
# set container port?
EXPOSE 3003
#