version: '3' # optional since v1.27.0
services:
  dev:
    # point to existing docker image
    image: csu12kj/mm-dev
    # provide name of container to run this in
    container_name: mm-dev-hot
    # access port (host) : docker container port (server)
    ports:
      - '8080:8080'
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    # script to run
    command: npm run dev:hot

# any "modules?" this depends on
# depends_on:
#   - postgres-db
# postgres-db:
#   image: csu12kj/mm-database
#   container_name: mm-pg-db
#   environment:
#     - POSTGRES_PASSWORD=admin
#     - POSTGRES_USER=mmadmin
#     - POSTGRES_DB=mmdb
#   volumes:
#     - dev-db-volume:/var/lib/postgresql/data

volumes:
  node_modules: {}
  dev-db-volume: {}
